### ISSUE TITLE
Revert color/style modification of CRAN title and sections

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/R_CRAN_Booster#6]
@chainsawriot, in your https://github.com/HenrikBengtsson/R_CRAN_Booster/pull/5, which I really like, you also tweaked the color(?) on the CRAN sections -  'Downloads', 'Reverse dependencies', and 'Linking' - as well as the title header, e.g.

![flameshot_2021-05-14T185429](https://user-images.githubusercontent.com/1616850/118344972-52d37680-b4e6-11eb-8df0-e3f41234f144.png)

Do you think you could undo that, so that the secondary color/style only applies to the injected components, e.g. "(153)"?

**Comment by chainsawriot** [comment]
@HenrikBengtsson Thanks for letting me know this. I didn't know the `--sec-color` in the current CRAN has changed. I adopted it from the CSS of an ancient version of CRAN, which `--sec-color` is defined as `rgb(55%, 55%, 55%)`. In the current version, it is defined as `rgb(40%, 40%, 40%)` (slightly darker).

I think a better solution is to define `--sec-color`  as `rgb(40%, 40%, 40%)` (the current CRAN default) and then we define our own `--aux-color` as `rgb(55%, 55%, 55%)`.

The entire CSS would be like this:

```css

@media (prefers-color-scheme: light) {
    :root {
	--background-color: white;
	--text-color: black;
	--link-color: blue;
	--sec-color: rgb(40%, 40%, 40%);
	--aux-color: rgb(55%, 55%, 55%);

    }
}

@media (prefers-color-scheme: dark) {
    :root {
	--background-color: #121212;
	--text-color: white;
	--link-color: #BB86FC;
	--sec-color: #03DAC5;
	--aux-color: #018786;
    }
}

body {
    background: var(--background-color);
    color: var(--text-color);
}

h1 {
    background: var(--background-color);
    color: var(--sec-color);
    font-family: monospace;
    font-size: x-large;
    text-align: center;
}

h2 {
    background: var(--background-color);
    color: var(--sec-color);
    font-family: monospace;
    font-size: large;
}

h3, h4, h5 {
    background: var(--background-color);
    color: var(--sec-color);
    font-family: monospace;
}

a {
    background: var(--background-color);
    color: var(--link-color);
}

em.navigation {
    font-weight: bold;
    font-style: normal;
    background: var(--background-color);
    color: var(--sec-color);
    font-family: monospace;
}

img.toplogo {
    vertical-align: middle;
}

span.check_ok {
    color: black;
}

span.check_ko {
    color: red;
}

span.BioC {
    color: #2C92A1;
}

span.Ohat {
    color: #8A4513;
}

span.Gcode {
    color: #5B8A00;
}

span.Rforge {
    color: #8009AA;
}

span.GitHub {
    color: #9F7BE1;
}

span.acronym {
    font-size: small;
}

span.env {
    font-family: monospace;
}

span.file {
    font-family: monospace;
}

span.option {
    font-family: monospace;
}

span.pkg {
    font-weight: bold;
}

span.samp {
    font-family: monospace;
}

button {
    background-color: var(--aux-color);
    color: var(--text-color);
}

input[type=text] {
    background-color: var(--background-color);
    color: var(--sec-color);
}

span.aux {
    background: var(--background-color);
    color: var(--aux-color);
}
```

Visually, it looks like this:

![Screenshot from 2021-05-15 13-44-38](https://user-images.githubusercontent.com/637269/118359703-01c68f80-b585-11eb-8713-c006aaef7310.png)

Or in dark mode:

![Screenshot from 2021-05-15 13-45-03](https://user-images.githubusercontent.com/637269/118359712-0db25180-b585-11eb-9587-0aeaf14a47df.png)

If you think it makes sense, then I can quickly send you a PR. Thank you!
